### ISSUE TITLE
Concern about `TrimCache` implementation of Pool class

### ISSUE THREAD

**Issue by BruceLiCong** [SeratoninRonin/CoroutineManager#1]
https://github.com/SeratoninRonin/CoroutineManager/blob/59a2c95560d79bb4cebca8935e6432ea9439d0d7/addons/CoroutineManager/PoolT.cs#L35

Should it be while (cacheCount < _objectQueue.Count) ?

**Comment by SeratoninRonin** [comment]
Yes it should, thanks

**Comment by SeratoninRonin** [comment]
Fixed
